CacheRoom/CacheRoom.Web/Areas/Admin/Models/Store/CollectionViewModel.cs
namespace CacheRoom.Web.Areas.Admin.Models.Store
{
    using System;
    using System.ComponentModel;
    using System.Linq.Expressions;
    using CacheRoom.Models;
    public class CollectionViewModel
    {
        public int Id { get; set; }

        [DisplayName("Име")]
        public string Name { get; set; }

        [DisplayName("Описание")]
        public string Description { get; set; }

        public static Expression<Func<Collection, CollectionViewModel>> ViewModel
        {
            get
            {
                return c => new CollectionViewModel()
                    {
                        Id = c.Id, Name = c.Name, Description = c.Description
                    };
            }
        }

    }
}

CacheRoom/CacheRoom.Web/Areas/Admin/Controllers/CollectionController.cs
namespace CacheRoom.Web.Areas.Admin.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using CacheRoom.Data.Contracts;
    using CacheRoom.Models;
    using CacheRoom.Web.Areas.Admin.Models.Store;
    using CacheRoom.Web.Controllers;
    using CacheRoom.Web.Extensions;

    using PagedList;
    public class CollectionController : BaseController
    {
        public CollectionController(ICacheRoomData data)
            : base(data)
        {
        }

        public ActionResult Index(int page = 1, int pageSize = 12)
        {
            return
                this.View(
                    this.Data.Collections.All()
                        .OrderByDescending(collection => collection.Name)
                        .Select(CollectionViewModel.ViewModel)
                        .ToPagedList(page,pageSize));

        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var collection = this.Data.Collections.Find(id);

            if (collection == null)
            {
                return this.HttpNotFound();
            }

            return this.View(collection);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CollectionViewModel collectionData)
        {
            var collections = this.Data.Collections.All().Select(c => c.Name);

            if (ModelState.IsValid)
            {
                if (collections.Contains(collectionData.Name))
                {
                    this.AddNotification("Вече съществува колекция с такова име. Моля задайте ново уникално име.", NotificationType.WARNING);

                    return this.View();
                }
                var collection = new Collection();
                collection.Name = collectionData.Name;
                collection.Description = collectionData.Description;

                this.Data.Collections.Add(collection);
                this.Data.SaveChanges();
                return RedirectToAction("Index");
            }

            return this.View(collectionData);
        }

        public ActionResult Edit(int? id, CollectionViewModel collectionData)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var collection =
                this.Data.Collections.All()
                    .Where(c => c.Id == id)
                    .Select(CollectionViewModel.ViewModel)
                    .FirstOrDefault();

            if (collection == null)
            {
                return this.HttpNotFound();
            }
            return this.View(collection);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,CollectionViewModel collectionData)
        {
            if (ModelState.IsValid)
            {
                var collection = this.Data.Collections.Find(id);
                collection.Name = collectionData.Name;
                collection.Description = collectionData.Description;

                this.Data.Collections.Update(collection);
                this.Data.SaveChanges();

                return this.RedirectToAction("Index");
            }

            return this.View(collectionData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([Bind(Include = "Id")] Collection collection)
        {
            this.Data.Collections.Delete(collection);
            this.Data.SaveChanges();
            return this.RedirectToAction("Index");
        }
    }
}

CacheRoom/CacheRoom.Web/Areas/Admin/Views/Collection/Create.cshtml
@model CacheRoom.Web.Areas.Admin.Models.Store.CollectionViewModel

@{
    ViewBag.Title = "Create";
    Layout = "../Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Collection", FormMethod.Post, new { @class = "form-horizontal admin" }))
{
    @Html.AntiForgeryToken()

    <fieldset class="admin-filedset">
        <legend>
            Създай колекция
        </legend>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-10">
                @Html.TextAreaFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>
        <div class="col-lg-10 col-lg-offset-2">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CacheRoom/CacheRoom.Web/Areas/Admin/Views/Collection/Edit.cshtml
@model CacheRoom.Web.Areas.Admin.Models.Store.CollectionViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "../Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "Collection", FormMethod.Post, new { @class = "form-horizontal admin" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)

    <fieldset class="admin-filedset">
        <legend>
            Редактирай колекция
        </legend>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-10">
                @Html.TextAreaFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>
        <div class="col-lg-10 col-lg-offset-2" >
            <input type="submit" value="Запази" class="btn btn-primary" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CacheRoom/CacheRoom.Web/Areas/Admin/Views/Collection/Index.cshtml
@model IEnumerable<CacheRoom.Web.Areas.Admin.Models.Store.CollectionViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "../Shared/_Layout.cshtml";

    var pagedList = (IPagedList)Model;
}
@using PagedList.Mvc;
@using PagedList;

<div id="admin-add-button" class="form-group">
    @Html.ActionLink("Създай нова", "Create", "Collection", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
</div>
<div class="row" id="admin-list-headers">
    <div class="col-xs-4">@Html.DisplayNameFor(model => model.Name)</div>
    <div class="col-xs-2">Редакция</div>
</div>

@foreach (var item in Model) {
    <div class="row" style="border-top: 2px solid slategray; background-color: #f9f9f9">
        <div style="margin-bottom: 45px; margin-top: 9px">

            <div class="col-xs-4">
                @Html.DisplayFor(modelItem => item.Name)
            </div>

            <div class="col-xs-2">
                @Html.Partial("_ItemActions", new ViewDataDictionary { { "ItemID", item.Id }, { "ItemType", "Collection" } })
            </div>
        </div>
    </div>
}
@Html.PagedListPager(pagedList, page => Url.Action("Index", new { page }))