CacheRoom/CacheRoom.Web/Areas/Admin/Controllers/BrandController.cs
namespace CacheRoom.Web.Areas.Admin.Controllers
{
    using System;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using CacheRoom.Data.Contracts;
    using CacheRoom.Models;
    using CacheRoom.Web.Areas.Admin.Models.Store;
    using CacheRoom.Web.Controllers;
    using CacheRoom.Web.Extensions;

    using PagedList;

    [Authorize(Roles = "AppAdmin")]
    public class BrandController : BaseController
    {
        public BrandController(ICacheRoomData data)
            : base(data)
        {
        }

        public ActionResult Index(int page = 1, int pageSize = 12)
        {
            return View(this.Data.Brands.All().OrderByDescending(brand => brand.Name)
                .Select(BrandViewModel.ViewModel)
                .ToPagedList(page, pageSize));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BrandViewModel brandData)
        {
            var brands = this.Data.Brands.All().Select(b => b.Name);

            if (ModelState.IsValid)
            {
                if (brands.Contains(brandData.Name))
                {
                    this.AddNotification("Вече съществува марка с такова име. Моля задайте ново уникално име.", NotificationType.WARNING);

                    return this.View();
                }
                var brand = new Brand();

                if (!String.IsNullOrWhiteSpace(brandData.Name))
                {
                    brand.Name = brandData.Name.Trim();
                }

                if (!String.IsNullOrWhiteSpace(brandData.Description))
                {
                    brand.Description = brandData.Description.Trim();
                }
                

                this.Data.Brands.Add(brand);
                this.Data.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(brandData);
        }

        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var brand = this.Data.Brands.All().Where(b => b.Id == id)
                .Select(BrandViewModel.ViewModel).FirstOrDefault();

            if (brand == null)
            {
                return this.HttpNotFound();
            }
            return this.View(brand);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, BrandViewModel brandData)
        {
            if (ModelState.IsValid)
            {
                var brand = this.Data.Brands.Find(id);
                brand.Name = brandData.Name;
                brand.Description = brandData.Description;

                this.Data.Brands.Update(brand);
                this.Data.SaveChanges();
                return this.RedirectToAction("Index");
            }
            return this.View(brandData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([Bind(Include = "Id")] Brand brand)
        {
            this.Data.Brands.Delete(brand);
            this.Data.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CacheRoom/CacheRoom.Web/Areas/Admin/Controllers/ProductController.cs
namespace CacheRoom.Web.Areas.Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.SqlTypes;
    using System.Diagnostics;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;

    using CacheRoom.Data.Contracts;
    using CacheRoom.Models;
    using CacheRoom.Web.Controllers;

    using PagedList;
    using System.Drawing;
    using System.Text;
    using System.Threading;

    using CacheRoom.Data;
    using CacheRoom.Web.Areas.Admin.Models.Store;
    using CacheRoom.Web.Extensions;
    using CacheRoom.Web.Search;

    using EntityFramework.Extensions;

    public class ProductController : BaseController
    {
        public ProductController(ICacheRoomData data)
            : base(data)
        {
        }

        public ActionResult Index()
        {
            var products =
                this.Data.Products.All()
                    .OrderByDescending(product => product.Name)
                    .Include(p => p.Brand)
                    .Include(p => p.Category)
                    .Include(p => p.ProductImages)
                    .Select(ProductViewModel.ViewModel)
                    .ToList();

            if (products.Any())
            {
                foreach (var p in products)
                {
                    p.Amount = this.Data.Quantities.All().Where(q => q.ProductId == p.Id).Sum(q => q.Amount) ?? 0;
                }
            }
            
            return this.View(products);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var product = this.Data.Products.Find(id);

            if (product == null)
            {
                return this.HttpNotFound();
            }

            return this.View(product);
        }

        private SelectList SetCollectionSelectList()
        {
            var collectionEmpty = new CollectionListViewModel() { Id = null, Name = "Без колекция" };

            var collections = this.Data.Collections.All().Select(CollectionListViewModel.ViewModel);

            var collectionsList = new List<CollectionListViewModel>();

            collectionsList.Add(collectionEmpty);

            foreach (var c in collections)
            {
                collectionsList.Add(c);
            }

            var collectionSelectList = new SelectList(collectionsList, "Id", "Name");

            return collectionSelectList;
        }

        public ActionResult Create()
        {
            if (!this.Data.Sizes.All().Any())
            {
                this.AddNotification(
                    "Няма създадени размери. Моля създайте размери, към които да задавате количества, при създаване на нов продукт.",
                    NotificationType.WARNING);
                return this.RedirectToAction("Create", "Size");
            }

            ViewBag.BrandId = new SelectList(this.Data.Brands.All(), "Id", "Name");
            ViewBag.CategoryId = new SelectList(this.Data.Categories.All(), "Id", "Name");


            ViewBag.CollectionId = this.SetCollectionSelectList();

            return this.View();
        }

        private void SetInitialSizes(Product product)
        {
            var category = this.Data.Categories.All().FirstOrDefault(c => c.Id == product.CategoryId);

            var categorySizes = this.Data.Sizes.All().Where(s => s.SizeType == category.SizeType).ToList();

            foreach (var size in categorySizes)
            {
                var quantity = new Quantity();

                quantity.SizeId = size.Id;
                quantity.ProductId = product.Id;
                quantity.Amount = 0;

                this.Data.Quantities.Add(quantity);
                this.Data.SaveChanges();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel productData)
        {
            var products = this.Data.Products.All().Select(p => p.Name.Trim());

            if (ModelState.IsValid)
            {
                if (products.Contains(productData.Name.Trim()))
                {
                    this.AddNotification(
                        "Вече съществува продукт с такова име. Моля задайте ново уникално име.",
                        NotificationType.WARNING);
                    ViewBag.BrandId = new SelectList(this.Data.Brands.All(), "Id", "Name");
                    ViewBag.CategoryId = new SelectList(this.Data.Categories.All(), "Id", "Name");
                    ViewBag.CollectionId = this.SetCollectionSelectList();

                    return this.RedirectToAction("Create");
                }
                var product = new Product();
                product.Name = productData.Name.Trim();
                product.CategoryId = productData.CategoryId;
                product.BrandId = productData.BrandId;
                product.Type = productData.Type;
                product.Price = productData.Price;
                product.Description = productData.Description;
                product.CollectionId = productData.CollectionId;
                product.IsOnSale = productData.IsOnSale;
                product.DateTimeCreated = DateTime.Now;

                this.Data.Products.Add(product);
                this.Data.SaveChanges();
                this.SetInitialSizes(product);

                this.UpdateLucene();
                return this.RedirectToAction("Add", "Quantity", new { id = product.Id });


            }

            ViewBag.BrandId = new SelectList(this.Data.Brands.All(), "Id", "Name", productData.BrandId);
            ViewBag.CategoryId = new SelectList(this.Data.Categories.All(), "Id", "Name", productData.CategoryId);

            return this.View(productData);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var product = this.Data.Products.Find(id);

            if (product == null)
            {
                return this.HttpNotFound();
            }

            ViewBag.BrandId = new SelectList(this.Data.Brands.All(), "Id", "Name", product.BrandId);
            ViewBag.CategoryID = new SelectList(this.Data.Categories.All(), "Id", "Name", product.CategoryId);

            return this.View(product);
        }

        private void ProcessDirectory(string startLocation)
        {
            foreach (var directory in Directory.GetDirectories(startLocation))
            {
                ProcessDirectory(directory);
                if (Directory.GetFiles(directory).Length == 0 && Directory.GetDirectories(directory).Length == 0)
                {
                    Directory.Delete(directory, false);
                }
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "Id,Name,CategoryId,BrandId,Type,IsOnSale,Price,OldPrice,Description")] Product product)
        {
            if (ModelState.IsValid)
            {
                var productUpdate = this.Data.Products.All().FirstOrDefault(p => p.Id == product.Id);
                var oldBrand = productUpdate.Brand.Name.Trim();
                var oldCategory = productUpdate.Category.Name.Trim();
                var oldProductName = productUpdate.Name.Trim();
                var updatedPathBase = String.Empty;
                var imageOldDirectory = String.Empty;
                var newBrand = string.Empty;
                var newCategory = string.Empty;
                var newProductName = string.Empty;
                var backupDirectory = "~/Images/temp";

                if (productUpdate != null)
                {
                    productUpdate.Name = product.Name;
                    productUpdate.CategoryId = product.CategoryId;
                    productUpdate.BrandId = product.BrandId;
                    productUpdate.Type = product.Type;
                    productUpdate.IsOnSale = product.IsOnSale;
                    productUpdate.Price = product.Price;
                    productUpdate.OldPrice = product.OldPrice;
                    productUpdate.Description = product.Description;
                    this.Data.Products.Update(productUpdate);
                    this.Data.SaveChanges();

                    var productUpdateImages =
                        this.Data.ProductImages.All().Where(i => i.ProductId == productUpdate.Id).ToList();

                    if (productUpdateImages.Any())
                    {
                        newBrand = productUpdate.Brand.Name.Trim();
                        newCategory = productUpdate.Category.Name.Trim();
                        newProductName = productUpdate.Name.Trim();

                        updatedPathBase = String.Format(
                            @"/Images/Products/{0}/{1}/{2}/",
                            newBrand,
                            newCategory,
                            newProductName);

                        imageOldDirectory = String.Format(
                            @"/Images/Products/{0}/{1}/{2}/",
                            oldBrand,
                            oldCategory,
                            oldProductName);

                        if (!updatedPathBase.Equals(imageOldDirectory))
                        {
                            if (!Directory.Exists(Server.MapPath(updatedPathBase)))
                            {
                                Directory.CreateDirectory(Server.MapPath(updatedPathBase));
                            }

                            foreach (var image in productUpdateImages)
                            {
                                var startImagePath = image.ImagePath.LastIndexOf('/');

CacheRoom/CacheRoom.Web/Areas/Admin/Controllers/SizeController.cs
namespace CacheRoom.Web.Areas.Admin.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using CacheRoom.Data.Contracts;
    using CacheRoom.Models;
    using CacheRoom.Web.Areas.Admin.Models.Store;
    using CacheRoom.Web.Controllers;
    using CacheRoom.Web.Extensions;

    using PagedList;
    public class SizeController : BaseController
    {
        public SizeController(ICacheRoomData data)
            : base(data)
        {
        }

        public ActionResult Index(int page = 1, int pageSize = 12)
        {
            return this.View(this.Data.Sizes.All().OrderByDescending(size => size.Label)
                .Select(SizeViewModel.ViewModel)
                .ToPagedList(page, pageSize));
        }

        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SizeViewModel sizeData)
        {
            var sizes = this.Data.Sizes.All().Select(s => s.Label);

            if (ModelState.IsValid)
            {
                if (sizes.Contains(sizeData.Label))
                {
                    this.AddNotification("Вече съществува размер с такова име. Моля задайте ново уникално име.", NotificationType.WARNING);

                    return this.View();
                }
                var size = new Size();
                size.Label = sizeData.Label;
                size.SizeType = sizeData.SizeType;

                this.Data.Sizes.Add(size);
                this.Data.SaveChanges();

                return this.RedirectToAction("Index");
            }

            return this.View(sizeData);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var size = this.Data.Sizes.All()
                .Where(s => s.Id == id)
                .Select(SizeViewModel.ViewModel)
                .FirstOrDefault();

            if (size == null)
            {
                return this.HttpNotFound();
            }

            return this.View(size);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SizeViewModel sizeData)
        {
            if (ModelState.IsValid)
            {
                var size = this.Data.Sizes.Find(id);
                size.Label = sizeData.Label;
                size.SizeType = sizeData.SizeType;

                this.Data.Sizes.Update(size);
                this.Data.SaveChanges();

                return this.RedirectToAction("Index");
            }

            return this.View(sizeData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([Bind(Include="Id")] Size size)
        {
            this.Data.Sizes.Delete(size);
            this.Data.SaveChanges();
            return this.RedirectToAction("Index");
        }

    }
}

CacheRoom/CacheRoom.Web/Areas/Admin/Views/Shared/_ItemActions.cshtml
@using (Html.BeginForm(Html.BeginForm("Delete", (string)ViewData["ItemType"], FormMethod.Post, new { style = "display: inline;" })))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(modelItem => ViewData["ItemId"], new { @Name = ViewData["ItemType"] + ".ID" })

    <button type="submit" class="btn btn-link">
        <i class="glyphicon glyphicon-remove"></i>
    </button>
}

CacheRoom/CacheRoom.Web/Areas/Admin/Views/Shared/_Layout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" id="admin-templates">
    <div class="col-sm-3" id="admin-menu-outer-div">
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="panel panel-default side-menu">
                <div class="panel-heading side-menu" role="tab" id="headingOne">
                    <h4 class="panel-title side-menu">
                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            <img src="@Url.Content("~/Content/images/admin/shop.png")"/>
                            <span>Магазин</span>
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body side-menu">
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Продукти", "Index", "Product", routeValues: null, htmlAttributes: new { title = "Products" })
                        </div>
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Категории", "Index", "Category", routeValues: null, htmlAttributes: new { title = "Categories" })
                        </div>
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Колекции", "Index", "Collection", routeValues: null, htmlAttributes: new { title = "Collections" })
                        </div>
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Марки", "Index", "Brand", routeValues: null, htmlAttributes: new { title = "Brands" })
                        </div>
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Размери", "Index", "Size", routeValues: null, htmlAttributes: new { title = "Sizes" })
                        </div>
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Заглавна Страница", "Index", "HomePage", routeValues: null, htmlAttributes: new { title = "HomePage" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default side-menu">
                <div class="panel-heading side-menu" role="tab" id="headingTwo">
                    <h4 class="panel-title side-menu">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            <img src="@Url.Content("~/Content/images/admin/blog.png")" />
                            <span>Блог</span>
                        </a>
                    </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                    <div class="panel-body side-menu">
                        <div class="button-in-admin-menu">
                            <a href="#/admin/add-video">Добавяне на видео</a>
                        </div>
                        <div class="button-in-admin-menu">
                            <a href="#/admin/add-article">Добавяне на статия</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default side-menu">
                <div class="panel-heading side-menu" role="tab" id="headingThree">
                    <h4 class="panel-title side-menu">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            <img src="@Url.Content("~/Content/images/admin/clients.png")"/>
                            <span>Поръчки</span>
                        </a>
                    </h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                    <div class="panel-body side-menu">
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Всички", "Index", "Shipment", routeValues: null, htmlAttributes: new { title = "All Shipments" })
                        </div>
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Изпратени", "Sended", "Shipment", routeValues: null, htmlAttributes: new { title = "Sended Shipments" })
                        </div>
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Необработени", "NotSended", "Shipment", routeValues: null, htmlAttributes: new { title = " Not Sended Shipments" })
                        </div>
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Отказани", "Canceled", "Shipment", routeValues: null, htmlAttributes: new { title = " Canceled" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default side-menu">
                <div class="panel-heading side-menu" role="tab" id="headingFour">
                    <h4 class="panel-title side-menu">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                            <img src="@Url.Content("~/Content/images/admin/info2.png")" />
                            <span>Информация</span>
                        </a>
                    </h4>
                </div>
                <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
                    <div class="panel-body side-menu">
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Всички", "All", "Shipment", routeValues: null, htmlAttributes: new { title = "All Shipments" })
                        </div>
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Изпратени", "Sended", "Shipment", routeValues: null, htmlAttributes: new { title = "Sended Shipments" })
                        </div>
                        <div class="button-in-admin-menu">
                            @Html.ActionLink("Необработени", "NotSended", "Shipment", routeValues: null, htmlAttributes: new { title = " Not Sended Shipments" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        @RenderBody()
    </div>
</div>

@section Scripts {
    @RenderSection("scripts", required: false)
}
@section styles {
    @Styles.Render("~/Content/bootstrap-datetimepicker")
}