CacheRoom/CacheRoom.Web/Areas/Admin/Models/Store/SizeViewModel.cs
namespace CacheRoom.Web.Areas.Admin.Models.Store
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq.Expressions;

    using CacheRoom.Models;

    public class SizeViewModel
    {
        public int Id { get; set; }

        [Required]
        [DisplayName("Етикет")]
        public string Label { get; set; }

        [Required]
        [DisplayName("Тип")]
        public SizeType SizeType { get; set; }

        public static Expression<Func<Size, SizeViewModel>> ViewModel
        {
            get
            {
                return s => new SizeViewModel()
                        {
                            Id = s.Id,
                            Label = s.Label, 
                            SizeType = s.SizeType
                        };
            }
        } 
    }
}

CacheRoom/CacheRoom.Web/Areas/Admin/Controllers/SizeController.cs
namespace CacheRoom.Web.Areas.Admin.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using CacheRoom.Data.Contracts;
    using CacheRoom.Models;
    using CacheRoom.Web.Areas.Admin.Models.Store;
    using CacheRoom.Web.Controllers;
    using CacheRoom.Web.Extensions;

    using PagedList;
    public class SizeController : BaseController
    {
        public SizeController(ICacheRoomData data)
            : base(data)
        {
        }

        public ActionResult Index(int page = 1, int pageSize = 12)
        {
            return this.View(this.Data.Sizes.All().OrderByDescending(size => size.Label)
                .Select(SizeViewModel.ViewModel)
                .ToPagedList(page, pageSize));
        }

        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SizeViewModel sizeData)
        {
            var sizes = this.Data.Sizes.All().Select(s => s.Label);

            if (ModelState.IsValid)
            {
                if (sizes.Contains(sizeData.Label))
                {
                    this.AddNotification("Вече съществува размер с такова име. Моля задайте ново уникално име.", NotificationType.WARNING);

                    return this.View();
                }
                var size = new Size();
                size.Label = sizeData.Label;
                size.SizeType = sizeData.SizeType;

                this.Data.Sizes.Add(size);
                this.Data.SaveChanges();

                return this.RedirectToAction("Index");
            }

            return this.View(sizeData);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var size = this.Data.Sizes.All()
                .Where(s => s.Id == id)
                .Select(SizeViewModel.ViewModel)
                .FirstOrDefault();

            if (size == null)
            {
                return this.HttpNotFound();
            }

            return this.View(size);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SizeViewModel sizeData)
        {
            if (ModelState.IsValid)
            {
                var size = this.Data.Sizes.Find(id);
                size.Label = sizeData.Label;
                size.SizeType = sizeData.SizeType;

                this.Data.Sizes.Update(size);
                this.Data.SaveChanges();

                return this.RedirectToAction("Index");
            }

            return this.View(sizeData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([Bind(Include="Id")] Size size)
        {
            this.Data.Sizes.Delete(size);
            this.Data.SaveChanges();
            return this.RedirectToAction("Index");
        }

    }
}

CacheRoom/CacheRoom.Web/Areas/Admin/Views/Size/Create.cshtml
@model CacheRoom.Web.Areas.Admin.Models.Store.SizeViewModel

@{
    ViewBag.Title = "Create";
    Layout = "../Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Size", FormMethod.Post, new { @class = "form-horizontal admin" }))
{
    @Html.AntiForgeryToken()

    <fieldset class="admin-filedset">
        <legend>
            Нов размер
        </legend>
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Label, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-10">
                @Html.TextBoxFor(model => model.Label, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Label)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SizeType, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-10">
                @Html.EnumDropDownListFor(model => model.SizeType, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SizeType)
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <input type="submit" value="Създай" class="btn btn-primary" />
            </div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CacheRoom/CacheRoom.Web/Areas/Admin/Views/Size/Edit.cshtml
@model CacheRoom.Web.Areas.Admin.Models.Store.SizeViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "../Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "Size", FormMethod.Post, new { @class = "form-horizontal admin" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)

    <fieldset>
        <legend class="admin-filedset">
            Редакция на размер
        </legend>
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Label, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-10">
                @Html.TextBoxFor(model => model.Label, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Label)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SizeType, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-10">
                @Html.EnumDropDownListFor(model => model.SizeType, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SizeType)
            </div>
        </div>
        <div style="margin-top: 15px" class="col-lg-10 col-lg-offset-2">
            <input type="submit" value="Запази" class="btn btn-primary" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CacheRoom/CacheRoom.Web/Areas/Admin/Views/Size/Index.cshtml
@model IEnumerable<CacheRoom.Web.Areas.Admin.Models.Store.SizeViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "../Shared/_Layout.cshtml";

    var pagedList = (IPagedList)Model;
}
@using PagedList.Mvc;
@using PagedList;

<div id="admin-add-button" class="form-group">
    @Html.ActionLink("Създай нов", "Create", "Size", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
</div>
<div class="row" id="admin-list-headers">
    <div class="col-xs-3">@Html.DisplayNameFor(model => model.Label)</div>
    <div class="col-xs-3">@Html.DisplayNameFor(model => model.SizeType)</div>
    <div class="col-xs-3">Редакция</div>
</div>
@foreach (var item in Model)
{
    <div class="row" ng-repeat="brand in brands" style="border-top: 2px solid slategray; background-color: #f9f9f9">
        <div style="margin-bottom: 45px; margin-top: 9px">
            <div class="col-xs-3">
                @Html.DisplayFor(modelItem => item.Label)
            </div>
            <div class="col-xs-3">
                @Html.DisplayFor(modelItem => item.SizeType)
            </div>
            <div class="col-xs-3">
                @Html.Partial("_ItemActions", new ViewDataDictionary { { "ItemID", item.Id }, { "ItemType", "Size" } })
            </div>
        </div>
    </div>
}
@Html.PagedListPager(pagedList, page => Url.Action("Index", new { page }))